version: '3.7'

services:
  product:
    image: product
    container_name: product_container
    depends_on:
        - product_db
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - '3031:80'

  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - product_db_data:/var/lib/postgresql/data/
volumes:
  product_db_data: